packages:
  - 'packages/lit-analyzer'
  - 'packages/ts-lit-plugin'
  - 'packages/vscode-lit-plugin'
  - 'packages/web-component-analyzer'
  - 'dev'

allowBuilds:
  "@vscode/vsce-sign": true
  esbuild: true
  husky: true
  keytar: true