name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Run

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [18, 20, 22]
        exclude:
          - os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint

      - name: test
        run: npm run test:headless

      - name: Package vscode plugin
        if: matrix.os == 'ubuntu-latest'
        run: npm run package && mv packages/vscode-lit-plugin/out/packaged.vsix vscode-lit-plugin.vsix

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest' && matrix.node == 22
        with:
          name: vscode-lit-plugin.vsix
          path: vscode-lit-plugin.vsix
